"""Pad-level chip_top sensor-I2C smoke test using project Python sensor models.

This test is for the real chip_top pad path, not the SIM-only sensor bus.
The Makefile target compiles chip_top RTL with CHIP_TOP_PAD_I2C=1, which keeps
`SIM` undefined so `src/i2c_master.sv` drives the physical sensor I2C pads:

    bidir_PAD[23] -> sensor SCL
    bidir_PAD[24] -> sensor SDA

The testbench wrapper exposes those pad nets as `sensor_scl_sample` and
`sensor_sda_sample`. This cocotb test attaches two open-drain I2C slave models
to the SDA pad via cocotbext-i2c-style `sda_o` signals:

    LIS2DW12 accelerometer at 7-bit address 0x19
    ADPD144RI PPG sensor at 7-bit address 0x64

The sensor payloads are generated by the repository's Python sensor models
(`scripts/sensor_models/sensors/accelerometer.py` and `ppg.py`) from small,
deterministic synthetic raw inputs. That means the test exercises:

    Python sensor model -> I2C register model -> chip_top pads ->
    GF180 IO model -> top/i2c_master -> accel_reader/ppg_fifo_reader

Pass criteria:
    * sensor SCL toggles on bidir_PAD[23]
    * the accelerometer init writes are observed over pads
    * at least one accelerometer data burst is read over pads
    * the PPG FIFO access-enable write is observed over pads
    * at least one PPG FIFO burst is read over pads
    * the internal accel_reader emits accel_valid_w
    * the internal ppg_fifo_reader emits ppg_sample_valid_w

This intentionally does not prove full feature correctness or ML/logit behavior.
It proves that real chip_top sensor-pad I2C traffic can reach sensor-like models
and return model-generated accel/PPG samples into the RTL.

Useful debug output:
    * the first decoded I2C address bytes seen on the pads
    * sensor-model transaction counters and last samples served
    * optional internal top/i2c_master/reader signals, when visible

Set I2C_PAD_VERBOSE=1 to print periodic snapshots while the test is running.
"""

import logging
import os
import sys
import tempfile
from pathlib import Path

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, ReadOnly, RisingEdge, Timer
from cocotbext.i2c import I2cDevice


SENSOR_SCL_PAD = 23
SENSOR_SDA_PAD = 24

TEST_MODE_MSSD = 0x1

ACC_ADDR = 0x19
PPG_ADDR = 0x64
ACC_REG_CTRL1 = 0x20
ACC_REG_RANGE = 0x23
ACC_REG_STATUS = 0x27
ACC_REG_OUT_X_L = 0x28
PPG_REG_STATUS = 0x00
PPG_REG_FIFO_THRESH = 0x06
PPG_REG_FIFO_ACCESS_ENA = 0x5F
PPG_REG_FIFO_ACCESS = 0x60
DEBUG_SNAPSHOT_PERIOD_CYCLES = 25_000

ROOT = Path(__file__).resolve().parents[3]
SENSOR_MODEL_DIR = ROOT / "scripts" / "sensor_models"
if str(SENSOR_MODEL_DIR) not in sys.path:
    sys.path.insert(0, str(SENSOR_MODEL_DIR))

import numpy as np
from sensors import accelerometer as accel_model
from sensors import ppg as ppg_model


async def _startup(dut):
    """Put chip_top in sensor debug mode and release reset.

    TEST_MODE_MSSD enables the sensor/feature path used by the existing pad
    bridge checks. The bidir drive signals are released except for SDA, where
    this test's I2C devices may pull the line low through open-drain controls.
    """

    dut.input_drv.value = TEST_MODE_MSSD
    dut.bidir_drv.value = 0
    dut.bidir_oe.value = 0
    dut.sensor_sda_drive_low.value = 0
    dut.accel_sda_o.value = 1
    dut.ppg_sda_o.value = 1
    dut.accel_scl_o.value = 1
    dut.ppg_scl_o.value = 1
    dut.rst_n_drv.value = 0
    cocotb.start_soon(Clock(dut.clk_drv, 40, "ns").start())
    await Timer(400, "ns")
    dut.rst_n_drv.value = 1


def _build_sensor_model_streams():
    """Generate deterministic digital streams with the project sensor models.

    The production model scripts normally write CSV files for SV simulations.
    Here we call the same processing functions directly and keep the returned
    arrays in memory, avoiding PhysioNet/network access during the cocotb run.
    """

    sample_count = int(os.getenv("I2C_PAD_SENSOR_MODEL_SAMPLES", "512"))
    rng_seed = int(os.getenv("I2C_PAD_SENSOR_MODEL_SEED", "7"))
    np.random.seed(rng_seed)

    accel_t = np.arange(sample_count, dtype=float) / 25.0
    raw_g = np.column_stack(
        [
            0.020 * np.sin(2 * np.pi * 0.25 * accel_t),
            0.015 * np.cos(2 * np.pi * 0.18 * accel_t),
            1.000 + 0.010 * np.sin(2 * np.pi * 0.11 * accel_t),
        ]
    )

    bpm_t = np.arange(0.0, max(12.0, sample_count / 25.0 + 4.0), 1.0)
    bpm = 64.0 + 3.0 * np.sin(2 * np.pi * bpm_t / 20.0)

    with tempfile.TemporaryDirectory(prefix="sensor_model_i2c_") as tmp:
        tmp_path = Path(tmp)
        accel_model.PLOT_DIR = str(tmp_path / "plots")
        ppg_model.PLOT_DIR = str(tmp_path / "plots")
        accel_counts = accel_model.process_accelerometer(raw_g, tmp_path)
        red_counts, _ir_counts = ppg_model.process_ppg(bpm_t, bpm, tmp_path)

    return accel_counts.astype(np.int16), red_counts.astype(np.uint16)


def _get_optional_handle(dut, path):
    handle = dut
    for name in path.split("."):
        try:
            handle = getattr(handle, name)
        except (AttributeError, ValueError):
            return None
    return handle


def _value_to_int(value):
    try:
        return value.to_unsigned()
    except (AttributeError, ValueError):
        try:
            return value.to_signed()
        except (AttributeError, ValueError):
            return None


def _format_signal(handle, width_hint=None):
    if handle is None:
        return "n/a"
    value = handle.value
    intval = _value_to_int(value)
    if intval is None:
        return str(value)
    if width_hint is not None:
        mask = (1 << width_hint) - 1
        return f"0x{intval & mask:0{max(1, (width_hint + 3) // 4)}x}"
    return str(intval)


def _collect_debug_handles(dut):
    """Collect optional internal handles that are useful when present in RTL."""

    base = "u_chip.i_chip_core.u_top"
    names = {
        "core_clk": "u_chip.i_chip_core.core_clk_w",
        "i2c_state": f"{base}.u_i2c_master.state_r",
        "i2c_sda_i": f"{base}.u_i2c_master.sda_i",
        "i2c_scl": f"{base}.u_i2c_master.scl_o",
        "i2c_sda_oe": f"{base}.u_i2c_master.sda_oe",
        "i2c_active_client": f"{base}.u_i2c_master.active_client",
        "i2c_byte_phase": f"{base}.u_i2c_master.byte_phase_r",
        "i2c_timer": f"{base}.u_i2c_master.timer_r",
        "acc_reader_state": f"{base}.u_accel_reader.state_r",
        "acc_reader_timeout": f"{base}.u_accel_reader.timeout_o",
        "acc_reader_nack": f"{base}.u_accel_reader.nack_seen_o",
        "acc_cmd_valid": f"{base}.acc_i2c_cmd_valid_w",
        "acc_cmd_addr": f"{base}.acc_i2c_cmd_addr_w",
        "acc_cmd_reg": f"{base}.acc_i2c_cmd_reg_w",
        "acc_cmd_write": f"{base}.acc_i2c_cmd_write_w",
        "acc_rsp_valid": f"{base}.acc_i2c_rsp_valid_w",
        "acc_rsp_data": f"{base}.acc_i2c_rsp_data_w",
        "acc_rsp_done": f"{base}.acc_i2c_rsp_done_w",
        "acc_rsp_err": f"{base}.acc_i2c_rsp_error_w",
        "accel_valid": f"{base}.accel_valid_w",
        "ax": f"{base}.ax_w",
        "ay": f"{base}.ay_w",
        "az": f"{base}.az_w",
        "accel_error": f"{base}.accel_error_w",
        "ppg_cmd_valid": f"{base}.ppg_i2c_cmd_valid_w",
        "ppg_reader_state": f"{base}.u_ppg_fifo_reader.state_r",
        "ppg_reader_error": f"{base}.u_ppg_fifo_reader.i2c_error_flag",
        "ppg_cmd_addr": f"{base}.ppg_i2c_cmd_addr_w",
        "ppg_cmd_reg": f"{base}.ppg_i2c_cmd_reg_w",
        "ppg_cmd_len": f"{base}.ppg_i2c_cmd_len_w",
        "ppg_cmd_write": f"{base}.ppg_i2c_cmd_write_w",
        "ppg_rsp_valid": f"{base}.ppg_i2c_rsp_valid_w",
        "ppg_rsp_data": f"{base}.ppg_i2c_rsp_data_w",
        "ppg_rsp_last": f"{base}.ppg_i2c_rsp_last_w",
        "ppg_rsp_done": f"{base}.ppg_i2c_rsp_done_w",
        "ppg_rsp_err": f"{base}.ppg_i2c_rsp_err_w",
        "ppg_sample_valid": f"{base}.ppg_sample_valid_w",
        "ppg_sample": f"{base}.ppg_sample_w",
        "ppg_sample_time": f"{base}.ppg_sample_time_w",
        "feat_valid": f"{base}.feat_valid_o",
        "ml_update_gate": f"{base}.ml_update_gate_o",
        "invalid_reason": f"{base}.invalid_reason_o",
    }
    return {name: _get_optional_handle(dut, path) for name, path in names.items()}


def _signal_is_high(handle):
    if handle is None:
        return False
    intval = _value_to_int(handle.value)
    return bool(intval)


def _sample_debug_values(handles):
    return {
        "i2c_state": _format_signal(handles["i2c_state"]),
        "i2c_extra": (
            _format_signal(handles["i2c_active_client"]),
            _format_signal(handles["i2c_byte_phase"]),
            _format_signal(handles["i2c_timer"]),
            _format_signal(handles["i2c_sda_i"]),
            _format_signal(handles["i2c_sda_oe"]),
        ),
        "reader_state": (
            _format_signal(handles["acc_reader_state"]),
            _format_signal(handles["acc_reader_timeout"]),
            _format_signal(handles["acc_reader_nack"]),
            _format_signal(handles["ppg_reader_state"]),
            _format_signal(handles["ppg_reader_error"]),
        ),
        "acc_cmd": (
            _format_signal(handles["acc_cmd_valid"]),
            _format_signal(handles["acc_cmd_addr"], 7),
            _format_signal(handles["acc_cmd_reg"], 8),
            _format_signal(handles["acc_cmd_write"]),
        ),
        "acc_rsp": (
            _format_signal(handles["acc_rsp_valid"]),
            _format_signal(handles["acc_rsp_data"], 8),
            _format_signal(handles["acc_rsp_done"]),
            _format_signal(handles["acc_rsp_err"]),
        ),
        "accel": (
            _format_signal(handles["accel_valid"]),
            _format_signal(handles["ax"], 16),
            _format_signal(handles["ay"], 16),
            _format_signal(handles["az"], 16),
            _format_signal(handles["accel_error"]),
        ),
        "ppg_cmd": (
            _format_signal(handles["ppg_cmd_valid"]),
            _format_signal(handles["ppg_cmd_addr"], 7),
            _format_signal(handles["ppg_cmd_reg"], 8),
            _format_signal(handles["ppg_cmd_len"], 8),
            _format_signal(handles["ppg_cmd_write"]),
        ),
        "ppg_rsp": (
            _format_signal(handles["ppg_rsp_valid"]),
            _format_signal(handles["ppg_rsp_data"], 8),
            _format_signal(handles["ppg_rsp_last"]),
            _format_signal(handles["ppg_rsp_done"]),
            _format_signal(handles["ppg_rsp_err"]),
        ),
        "ppg_sample": (
            _format_signal(handles["ppg_sample_valid"]),
            _format_signal(handles["ppg_sample"], 16),
            _format_signal(handles["ppg_sample_time"], 32),
        ),
        "feature": (
            _format_signal(handles["feat_valid"]),
            _format_signal(handles["ml_update_gate"]),
            _format_signal(handles["invalid_reason"], 8),
        ),
    }


def _log_debug_summary(log, dut, accel, ppg, addr_monitor, handles, pulse_counts):
    values = _sample_debug_values(handles)
    log.info(
        "pad summary: scl=%s sda=%s accel_sda_o=%s ppg_sda_o=%s addr_bytes=%s",
        _format_signal(dut.sensor_scl_sample),
        _format_signal(dut.sensor_sda_sample),
        _format_signal(dut.accel_sda_o),
        _format_signal(dut.ppg_sda_o),
        [hex(b) for b in addr_monitor.addr_bytes[:16]],
    )
    log.info(
        "sensor model summary: accel_ctrl_writes=%d accel_range_writes=%d accel_reads=%d "
        "last_accel=%s ppg_fifo_en_writes=%d ppg_fifo_reads=%d ppg_samples=%d last_ppg=0x%04x",
        accel.ctrl_writes,
        accel.range_writes,
        accel.sample_reads,
        accel.last_sample,
        ppg.fifo_en_writes,
        ppg.fifo_reads,
        ppg.index,
        ppg.last_sample,
    )
    log.info(
        "internal pulse counts: acc_rsp_valid=%d accel_valid=%d ppg_rsp_valid=%d "
        "ppg_sample_valid=%d feat_valid=%d",
        pulse_counts["acc_rsp_valid"],
        pulse_counts["accel_valid"],
        pulse_counts["ppg_rsp_valid"],
        pulse_counts["ppg_sample_valid"],
        pulse_counts["feat_valid"],
    )
    log.info(
        "last internal snapshot: i2c_state=%s acc_cmd(valid,addr,reg,wr)=%s "
        "acc_rsp(valid,data,done,err)=%s accel(valid,ax,ay,az,err)=%s",
        values["i2c_state"],
        values["acc_cmd"],
        values["acc_rsp"],
        values["accel"],
    )
    log.info(
        "last internal snapshot: i2c_extra(active,phase,timer,sda_i,sda_oe)=%s "
        "reader_state(acc,acc_timeout,acc_nack,ppg,ppg_err)=%s",
        values["i2c_extra"],
        values["reader_state"],
    )
    log.info(
        "last internal snapshot: ppg_cmd(valid,addr,reg,len,wr)=%s "
        "ppg_rsp(valid,data,last,done,err)=%s ppg_sample(valid,value,time)=%s "
        "feature(valid,gate,invalid_reason)=%s",
        values["ppg_cmd"],
        values["ppg_rsp"],
        values["ppg_sample"],
        values["feature"],
    )


class PulseMonitor:
    """Edge-triggered monitor for one-cycle RTL pulses."""

    def __init__(self, handle, sample_fn=None):
        self.handle = handle
        self.sample_fn = sample_fn
        self.count = 0
        self.samples = []

    async def run(self):
        if self.handle is None:
            return
        while True:
            await RisingEdge(self.handle)
            await ReadOnly()
            self.count += 1
            if self.sample_fn is not None:
                self.samples.append(self.sample_fn())


class RegisterSensorDevice(I2cDevice):
    """Base class for simple register-addressed I2C sensor devices.

    It subclasses cocotbext-i2c so the device owns/release-drives SDA through
    the same open-drain style interface as cocotbext. The byte sampler is kept
    tolerant of this chip_top pad simulation's edge ordering; the stock
    cocotbext state machine was seeing false stop/repeated-start tokens while
    the passive monitor still decoded valid address bytes.
    """

    def __init__(self, *args, addr, **kwargs):
        self.addr = addr
        self.reg_ptr = 0
        self._first_write = True
        self._read_buf = []
        self.transactions = 0
        self.writes = 0
        self.reads = 0
        self.seen = False
        self.observed_tokens = []
        self._pending_start = False
        super().__init__(*args, **kwargs)

    def _scl_is_high(self):
        return str(self.scl.value) == "1"

    def _sda_is_high(self):
        return str(self.sda.value) == "1"

    async def _wait_start(self):
        if self._pending_start:
            self._pending_start = False
            return
        while True:
            await FallingEdge(self.sda)
            await ReadOnly()
            if self._scl_is_high():
                return

    async def _recv_byte(self, record=True):
        value = 0
        for bit in range(7, -1, -1):
            await RisingEdge(self.scl)
            await ReadOnly()
            if self._sda_is_high():
                value |= 1 << bit
        if record:
            self.observed_tokens.append(value)
        return value

    def handle_start(self):
        self._first_write = True
        self._read_buf = []

    async def handle_write(self, data):
        self.seen = True
        if self._first_write:
            self.reg_ptr = data
            self._first_write = False
        else:
            self.writes += 1
            self.handle_reg_write(self.reg_ptr, data)
            self.reg_ptr = (self.reg_ptr + 1) & 0xFF

    async def handle_read(self):
        self.seen = True
        if not self._read_buf:
            self._read_buf = list(self.make_read_response(self.reg_ptr))
        data = self._read_buf.pop(0) if self._read_buf else 0
        if not self._read_buf:
            self.reg_ptr = (self.reg_ptr + 1) & 0xFF
        self.reads += 1
        return data

    def handle_stop(self):
        self.transactions += 1
        self._first_write = True
        self._read_buf = []

    def handle_reg_write(self, reg, data):
        pass

    def make_read_response(self, reg):
        return [0]

    def is_data_write_reg(self, reg):
        return False

    async def _send_ack(self):
        await FallingEdge(self.scl)
        self._set_sda(0)
        await RisingEdge(self.scl)
        await FallingEdge(self.scl)
        self._set_sda(1)

    async def _send_byte(self, value):
        for bit in range(7, -1, -1):
            if self._scl_is_high():
                await FallingEdge(self.scl)
            self._set_sda((value >> bit) & 1)
            await RisingEdge(self.scl)
        await FallingEdge(self.scl)
        self._set_sda(1)
        await RisingEdge(self.scl)
        await ReadOnly()
        master_nack = self._sda_is_high()
        await FallingEdge(self.scl)
        return not master_nack

    async def _send_read_response(self, reg):
        response = list(self.make_read_response(reg))
        byte_index = 0
        while True:
            byte = response[byte_index] if byte_index < len(response) else 0x00
            byte_index += 1
            if not await self._send_byte(byte):
                return

    async def _run(self):
        """Handle write-reg/read-data and write-reg/write-data transactions."""

        self._set_sda(1)
        while True:
            await self._wait_start()
            self.handle_start()

            addr_rw = await self._recv_byte()
            addr = (addr_rw >> 1) & 0x7F
            read = bool(addr_rw & 1)
            if addr != self.addr:
                continue

            self.seen = True
            await self._send_ack()

            if read:
                await self._send_read_response(self.reg_ptr)
                self.transactions += 1
                continue

            reg = await self._recv_byte(record=False)
            await self.handle_write(reg)
            await self._send_ack()

            if self.is_data_write_reg(reg):
                data = await self._recv_byte(record=False)
                await self.handle_write(data)
                await self._send_ack()
                self.transactions += 1
                continue

            await self._wait_start()
            self.handle_start()
            addr_rw = await self._recv_byte()
            read_addr = (addr_rw >> 1) & 0x7F
            if read_addr != self.addr or not (addr_rw & 1):
                raise AssertionError(
                    f"unexpected repeated-start address 0x{addr_rw:02x} for device 0x{self.addr:02x}"
                )
            await self._send_ack()
            await self._send_read_response(reg)
            self.transactions += 1


class PassiveI2CAddressMonitor:
    """Non-driving monitor used to debug what the chip puts on the sensor pads.

    On timeout, the first decoded address bytes help distinguish pad activity
    problems from missing/incorrect sensor responses. Expected early bytes are
    usually 0x32 for ACC_ADDR write and 0xc8 for PPG_ADDR write.
    """

    def __init__(self, dut):
        self.dut = dut
        self.addr_bytes = []

    def _scl_is_high(self):
        return str(self.dut.sensor_scl_sample.value) == "1"

    def _sda_is_high(self):
        return str(self.dut.sensor_sda_sample.value) == "1"

    async def _wait_start(self):
        while True:
            await FallingEdge(self.dut.sensor_sda_sample)
            await ReadOnly()
            if self._scl_is_high():
                return

    async def _recv_byte(self):
        value = 0
        for bit in range(7, -1, -1):
            await RisingEdge(self.dut.sensor_scl_sample)
            await ReadOnly()
            if self._sda_is_high():
                value |= 1 << bit
        return value

    async def run(self):
        while True:
            await self._wait_start()
            self.addr_bytes.append(await self._recv_byte())


class Lis2dw12Device(RegisterSensorDevice):
    """LIS2DW12-like register behavior backed by accelerometer.py samples."""

    def __init__(self, *args, samples, **kwargs):
        self.samples = samples
        self.index = 0
        self.ctrl_writes = 0
        self.range_writes = 0
        self.sample_reads = 0
        self.last_sample = None
        super().__init__(*args, addr=ACC_ADDR, **kwargs)

    def handle_reg_write(self, reg, data):
        if reg == ACC_REG_CTRL1:
            self.ctrl_writes += 1
        elif reg == ACC_REG_RANGE:
            self.range_writes += 1

    def is_data_write_reg(self, reg):
        return reg in (ACC_REG_CTRL1, ACC_REG_RANGE)

    def make_read_response(self, reg):
        # STATUS reports data-ready. OUT_X_L returns XL/XH/YL/YH/ZL/ZH, matching
        # the existing SV sensor model's left-justified 14-bit sample format.
        if reg == ACC_REG_STATUS:
            return [0x01]
        if reg == ACC_REG_OUT_X_L:
            if self.index >= len(self.samples):
                self.index = 0
            sample = self.samples[self.index]
            self.index += 1
            self.sample_reads += 1
            self.last_sample = tuple(int(v) for v in sample)
            ax = (int(sample[0]) << 2) & 0xFFFF
            ay = (int(sample[1]) << 2) & 0xFFFF
            az = (int(sample[2]) << 2) & 0xFFFF
            return [ax & 0xFF, ax >> 8, ay & 0xFF, ay >> 8, az & 0xFF, az >> 8]
        return [0x00]


class Adpd144riDevice(RegisterSensorDevice):
    """ADPD144RI-like register behavior backed by ppg.py red-channel samples."""

    def __init__(self, *args, samples, **kwargs):
        self.samples = samples
        self.index = 0
        self.fifo_en_writes = 0
        self.fifo_reads = 0
        self._last_sample = 0
        self.last_sample = 0
        super().__init__(*args, addr=PPG_ADDR, **kwargs)

    def handle_reg_write(self, reg, data):
        if reg == PPG_REG_FIFO_ACCESS_ENA:
            self.fifo_en_writes += 1

    def is_data_write_reg(self, reg):
        return reg == PPG_REG_FIFO_ACCESS_ENA

    def _next_fifo_byte(self, byte_index):
        if byte_index % 2 == 0:
            if self.index >= len(self.samples):
                self.index = 0
            sample = int(self.samples[self.index]) & 0x3FFF
            self.index += 1
            self._last_sample = sample
            self.last_sample = sample
            return sample & 0xFF
        return (self._last_sample >> 8) & 0xFF

    def make_read_response(self, reg):
        # The FIFO path streams 16-bit little-endian words from the generated
        # PPG red-channel counts, matching what ppg_fifo_reader consumes.
        if reg == PPG_REG_STATUS:
            return [0x00, 0x10]
        if reg == PPG_REG_FIFO_THRESH:
            return [0x00, 0x02]
        if reg == PPG_REG_FIFO_ACCESS:
            self.fifo_reads += 1
            return [self._next_fifo_byte(i) for i in range(16)]
        return [0x00]


@cocotb.test()
async def test_chip_top_i2c_pads_reach_cocotbext_sensor_models(dut):
    """Drive chip_top sensor pads and require both sensor models to be reached.

    The DUT drives SCL/SDA through the real pad-level path. This test only
    supplies external open-drain sensor responses; it does not poke internal
    sim bus signals or force feature outputs.
    """

    log = dut._log
    accel_samples, ppg_samples = _build_sensor_model_streams()
    await _startup(dut)

    accel = Lis2dw12Device(
        sda=dut.sensor_sda_sample,
        sda_o=dut.accel_sda_o,
        scl=dut.sensor_scl_sample,
        scl_o=dut.accel_scl_o,
        samples=accel_samples,
    )
    ppg = Adpd144riDevice(
        sda=dut.sensor_sda_sample,
        sda_o=dut.ppg_sda_o,
        scl=dut.sensor_scl_sample,
        scl_o=dut.ppg_scl_o,
        samples=ppg_samples,
    )
    accel.log.setLevel(logging.WARNING)
    ppg.log.setLevel(logging.WARNING)

    # This monitor never drives SDA. It is only here to make failures actionable
    # by showing which 8-bit address phases were visible on the physical pads.
    addr_monitor = PassiveI2CAddressMonitor(dut)
    cocotb.start_soon(addr_monitor.run())

    debug_handles = _collect_debug_handles(dut)
    verbose = os.getenv("I2C_PAD_VERBOSE", "0") == "1"
    pulse_monitors = {
        "acc_rsp_valid": PulseMonitor(
            debug_handles["acc_rsp_valid"],
            lambda: (
                _format_signal(debug_handles["acc_rsp_data"], 8),
                _format_signal(debug_handles["acc_rsp_done"]),
                _format_signal(debug_handles["acc_rsp_err"]),
            ),
        ),
        "accel_valid": PulseMonitor(
            debug_handles["accel_valid"],
            lambda: (
                _format_signal(debug_handles["ax"], 16),
                _format_signal(debug_handles["ay"], 16),
                _format_signal(debug_handles["az"], 16),
            ),
        ),
        "ppg_rsp_valid": PulseMonitor(
            debug_handles["ppg_rsp_valid"],
            lambda: (
                _format_signal(debug_handles["ppg_rsp_data"], 8),
                _format_signal(debug_handles["ppg_rsp_last"]),
                _format_signal(debug_handles["ppg_rsp_err"]),
            ),
        ),
        "ppg_sample_valid": PulseMonitor(
            debug_handles["ppg_sample_valid"],
            lambda: (
                _format_signal(debug_handles["ppg_sample"], 16),
                _format_signal(debug_handles["ppg_sample_time"], 32),
            ),
        ),
        "feat_valid": PulseMonitor(debug_handles["feat_valid"]),
    }
    for monitor in pulse_monitors.values():
        cocotb.start_soon(monitor.run())

    def pulse_counts():
        return {name: monitor.count for name, monitor in pulse_monitors.items()}

    saw_scl_toggle = False
    last_scl = str(dut.sensor_scl_sample.value)
    max_cycles = int(os.getenv("I2C_PAD_MAX_CYCLES", "250000"))
    post_observe_cycles = int(os.getenv("I2C_PAD_POST_OBSERVE_CYCLES", "10000"))
    reached_models_cycle = None
    sample_clock = debug_handles["core_clk"] if debug_handles["core_clk"] is not None else dut.clk_drv

    for cycle in range(max_cycles):
        await RisingEdge(sample_clock)
        await ReadOnly()
        scl = str(dut.sensor_scl_sample.value)
        saw_scl_toggle = saw_scl_toggle or (scl != last_scl)
        last_scl = scl

        if verbose and cycle and cycle % DEBUG_SNAPSHOT_PERIOD_CYCLES == 0:
            _log_debug_summary(log, dut, accel, ppg, addr_monitor, debug_handles, pulse_counts())

        if accel.sample_reads > 0 and ppg.fifo_reads > 0 and reached_models_cycle is None:
            reached_models_cycle = cycle
            log.info(
                "pad I2C reached both models at cycle %d: accel_samples=%d ppg_fifo_reads=%d ppg_samples=%d",
                cycle,
                accel.sample_reads,
                ppg.fifo_reads,
                ppg.index,
            )

        readers_consumed = (
            pulse_monitors["accel_valid"].count > 0 and pulse_monitors["ppg_sample_valid"].count > 0
        )
        if reached_models_cycle is not None and readers_consumed and cycle - reached_models_cycle >= post_observe_cycles:
            break
    else:
        _log_debug_summary(log, dut, accel, ppg, addr_monitor, debug_handles, pulse_counts())
        # The extra counters separate "no pad clocks", "wrong address",
        # "init never completed", and "data FIFO never reached" failures.
        raise AssertionError(
            "timed out waiting for cocotbext I2C sensor traffic; "
            f"scl_toggle={saw_scl_toggle}, "
            f"accel_seen={accel.seen}, accel_samples={accel.sample_reads}, "
            f"accel_ctrl_writes={accel.ctrl_writes}, accel_range_writes={accel.range_writes}, "
            f"ppg_seen={ppg.seen}, ppg_fifo_en_writes={ppg.fifo_en_writes}, "
            f"ppg_fifo_reads={ppg.fifo_reads}, "
            f"accel_tokens={accel.observed_tokens[:16]}, "
            f"ppg_tokens={ppg.observed_tokens[:16]}, "
            f"addr_bytes={[hex(b) for b in addr_monitor.addr_bytes[:16]]}"
        )

    _log_debug_summary(log, dut, accel, ppg, addr_monitor, debug_handles, pulse_counts())
    log.info(
        "internal pulse samples: acc_rsp=%s accel_valid=%s ppg_rsp=%s ppg_sample=%s",
        pulse_monitors["acc_rsp_valid"].samples[:12],
        pulse_monitors["accel_valid"].samples[:4],
        pulse_monitors["ppg_rsp_valid"].samples[:20],
        pulse_monitors["ppg_sample_valid"].samples[:8],
    )

    assert saw_scl_toggle, "sensor SCL pad did not toggle"
    assert accel.ctrl_writes > 0, "accelerometer CTRL1 init write was not observed"
    assert accel.range_writes > 0, "accelerometer range init write was not observed"
    assert accel.sample_reads > 0, "accelerometer data was not read through pads"
    assert ppg.fifo_en_writes > 0, "PPG FIFO access enable write was not observed"
    assert ppg.fifo_reads > 0, "PPG FIFO data was not read through pads"
    assert pulse_monitors["accel_valid"].count > 0, "accelerometer reader did not emit accel_valid_w"
    assert pulse_monitors["ppg_sample_valid"].count > 0, "PPG FIFO reader did not emit ppg_sample_valid_w"
